"""Employee Management

Revision ID: 12c34f4d1dfb
Revises: 
Create Date: 2024-09-28 11:02:46.149047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c34f4d1dfb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklistToken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fistname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female', name='gender'), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('account_status', sa.Enum('Active', 'Inactive', name='accountstatus'), nullable=False),
    sa.Column('contract_type', sa.Enum('Cdi', 'Cdd', 'Sivp', 'Apprenti', name='contracttype'), nullable=False),
    sa.Column('cnss_number', sa.Integer(), nullable=False),
    sa.CheckConstraint(
    "(contract_type IN ('Cdi', 'Cdd') AND cnss_number IS NOT NULL AND cnss_number::TEXT ~ '^\\d{8}-\\d{2}$') OR "
    "(contract_type IN ('Apprenti', 'Sivp') AND (cnss_number IS NULL OR cnss_number::TEXT ~ '^\\d{8}-\\d{2}$'))", 
    name='employee_contract_check'
),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnss_number'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accountActivation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('create_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('Used', 'Pending', name='tokenstatus'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('changePassword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('create_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('Used', 'Pending', name='tokenstatus'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employeeRole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('Superuser', 'Admin', 'Vendor', 'InventoryManager', name='roletype'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employeeRole')
    op.drop_table('changePassword')
    op.drop_table('accountActivation')
    op.drop_table('employees')
    op.drop_table('blacklistToken')
    # ### end Alembic commands ###
