"""Change created_on column 

Revision ID: a92f2d0d3bf3
Revises: fe729cf3ec5b
Create Date: 2024-11-09 13:23:05.196323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92f2d0d3bf3'
down_revision: Union[str, None] = 'fe729cf3ec5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
